language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
#  - osx

install:
  - pip install --user benchupload

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-5.0

# bob-bench xUnit file analysis
after_success:
  - benchupload --dir=$SMALLTALK_CI_BUILD
after_failure:
  - benchupload --dir=$SMALLTALK_CI_BUILD
